<#assign className = table.className>   
<#assign classNameLower = className?uncap_first>  
<#assign classNameLowerCase = className?lower_case>
<#assign targetpackage = targetpackage>


<#assign pid="business_manager" />
<#if table.sqlName?starts_with("t_")>
<#assign pid="system_manager" />
</#if>


INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_list', '${table.tableAlias}管理', ',system_manager,${table.sqlName}_list,', '${table.tableAlias}管理', 'system_manager', NULL, '/api/${targetpackage}/${classNameLowerCase}/list', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);
INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_update', '修改${table.tableAlias}', ',system_manager,${table.sqlName}_list,${table.sqlName}_update,', '修改${table.tableAlias}', '${table.sqlName}_list', NULL, '/api/${targetpackage}/${classNameLowerCase}/update', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);
INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_look', '查看${table.tableAlias}', ',system_manager,${table.sqlName}_list,${table.sqlName}_look,', '查看${table.tableAlias}', '${table.sqlName}_list', NULL, '/api/${targetpackage}/${classNameLowerCase}/look', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);
INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_export', '导出${table.tableAlias}', ',system_manager,${table.sqlName}_list,${table.sqlName}_export,', '导出${table.tableAlias}', '${table.sqlName}_list', NULL, '/api/${targetpackage}/${classNameLowerCase}/export', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);
INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_deletemore', '批量删除${table.tableAlias}', ',system_manager,${table.sqlName}_list,${table.sqlName}_deletemore,', '批量删除${table.tableAlias}', '${table.sqlName}_list', NULL, '/api/${targetpackage}/${classNameLowerCase}/delete/more', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);
INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_delete', '删除${table.tableAlias}', ',system_manager,${table.sqlName}_list,${table.sqlName}_delete,', '删除${table.tableAlias}', '${table.sqlName}_list', NULL, '/api/${targetpackage}/${classNameLowerCase}/delete', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);
INSERT INTO `t_menu`(`id`, `name`, `comcode`, `title`, `pid`, `remark`, `pageurl`, `menuType`, `path`, `keepAlive`, `component`, `permission`, `redirect`, `icon`, `createTime`, `createUserId`, `updateTime`, `updateUserId`, `sortno`, `active`) VALUES ('${table.sqlName}_upload', '导入${table.tableAlias}', ',system_manager,${table.sqlName}_list,${table.sqlName}_upload,', '导入${table.tableAlias}', '${table.sqlName}_list', NULL, '/api/${targetpackage}/${classNameLowerCase}/upload', 0, NULL, NULL, NULL, NULL, NULL, NULL, '${now?string("yyyy-MM-dd HH:mm:ss")}', '', '${now?string("yyyy-MM-dd HH:mm:ss")}', '', 0, 1);


INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_list_admin', 'r_10001', '${table.sqlName}_list', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');
INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_update_admin', 'r_10001', '${table.sqlName}_update', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');
INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_look_admin', 'r_10001', '${table.sqlName}_look', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');
INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_export_admin', 'r_10001', '${table.sqlName}_export', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');
INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_deletemore_admin', 'r_10001', '${table.sqlName}_deletemore', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');
INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_delete_admin', 'r_10001', '${table.sqlName}_delete', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');
INSERT INTO `t_role_menu`(`id`, `roleId`, `menuId`, `createTime`, `createUserId`, `updateTime`, `updateUserId`) VALUES ('${table.sqlName}_upload_admin', 'r_10001', '${table.sqlName}_upload', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001', '${now?string("yyyy-MM-dd HH:mm:ss")}', 'u_10001');



