// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommonService.proto

package net.shengjian.rpc.grpcauto;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes response = 1;</code>
   * @return The response.
   */
  com.google.protobuf.ByteString getResponse();
}
