// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommonService.proto

package net.shengjian.rpc.grpcauto;

/**
 * <pre>
 * 定义通用的 Grpc 请求体
 * </pre>
 *
 * Protobuf type {@code CommonRequest}
 */
public final class CommonRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CommonRequest)
    CommonRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommonRequest.newBuilder() to construct.
  private CommonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommonRequest() {
    request_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommonRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommonRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            serialize_ = input.readInt32();
            break;
          }
          case 18: {

            request_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.shengjian.rpc.grpcauto.GrpcAutoCreateService.internal_static_CommonRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.shengjian.rpc.grpcauto.GrpcAutoCreateService.internal_static_CommonRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.shengjian.rpc.grpcauto.CommonRequest.class, net.shengjian.rpc.grpcauto.CommonRequest.Builder.class);
  }

  public static final int SERIALIZE_FIELD_NUMBER = 1;
  private int serialize_;
  /**
   * <code>int32 serialize = 1;</code>
   * @return The serialize.
   */
  @java.lang.Override
  public int getSerialize() {
    return serialize_;
  }

  public static final int REQUEST_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString request_;
  /**
   * <code>bytes request = 2;</code>
   * @return The request.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRequest() {
    return request_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (serialize_ != 0) {
      output.writeInt32(1, serialize_);
    }
    if (!request_.isEmpty()) {
      output.writeBytes(2, request_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serialize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, serialize_);
    }
    if (!request_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, request_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.shengjian.rpc.grpcauto.CommonRequest)) {
      return super.equals(obj);
    }
    net.shengjian.rpc.grpcauto.CommonRequest other = (net.shengjian.rpc.grpcauto.CommonRequest) obj;

    if (getSerialize()
        != other.getSerialize()) return false;
    if (!getRequest()
        .equals(other.getRequest())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERIALIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSerialize();
    hash = (37 * hash) + REQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getRequest().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static net.shengjian.rpc.grpcauto.CommonRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.shengjian.rpc.grpcauto.CommonRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义通用的 Grpc 请求体
   * </pre>
   *
   * Protobuf type {@code CommonRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CommonRequest)
      net.shengjian.rpc.grpcauto.CommonRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.shengjian.rpc.grpcauto.GrpcAutoCreateService.internal_static_CommonRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.shengjian.rpc.grpcauto.GrpcAutoCreateService.internal_static_CommonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.shengjian.rpc.grpcauto.CommonRequest.class, net.shengjian.rpc.grpcauto.CommonRequest.Builder.class);
    }

    // Construct using net.shengjian.rpc.grpcauto.CommonRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serialize_ = 0;

      request_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.shengjian.rpc.grpcauto.GrpcAutoCreateService.internal_static_CommonRequest_descriptor;
    }

    @java.lang.Override
    public net.shengjian.rpc.grpcauto.CommonRequest getDefaultInstanceForType() {
      return net.shengjian.rpc.grpcauto.CommonRequest.getDefaultInstance();
    }

    @java.lang.Override
    public net.shengjian.rpc.grpcauto.CommonRequest build() {
      net.shengjian.rpc.grpcauto.CommonRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.shengjian.rpc.grpcauto.CommonRequest buildPartial() {
      net.shengjian.rpc.grpcauto.CommonRequest result = new net.shengjian.rpc.grpcauto.CommonRequest(this);
      result.serialize_ = serialize_;
      result.request_ = request_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.shengjian.rpc.grpcauto.CommonRequest) {
        return mergeFrom((net.shengjian.rpc.grpcauto.CommonRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.shengjian.rpc.grpcauto.CommonRequest other) {
      if (other == net.shengjian.rpc.grpcauto.CommonRequest.getDefaultInstance()) return this;
      if (other.getSerialize() != 0) {
        setSerialize(other.getSerialize());
      }
      if (other.getRequest() != com.google.protobuf.ByteString.EMPTY) {
        setRequest(other.getRequest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      net.shengjian.rpc.grpcauto.CommonRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (net.shengjian.rpc.grpcauto.CommonRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int serialize_ ;
    /**
     * <code>int32 serialize = 1;</code>
     * @return The serialize.
     */
    @java.lang.Override
    public int getSerialize() {
      return serialize_;
    }
    /**
     * <code>int32 serialize = 1;</code>
     * @param value The serialize to set.
     * @return This builder for chaining.
     */
    public Builder setSerialize(int value) {
      
      serialize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 serialize = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerialize() {
      
      serialize_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString request_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes request = 2;</code>
     * @return The request.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequest() {
      return request_;
    }
    /**
     * <code>bytes request = 2;</code>
     * @param value The request to set.
     * @return This builder for chaining.
     */
    public Builder setRequest(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      request_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes request = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequest() {
      
      request_ = getDefaultInstance().getRequest();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CommonRequest)
  }

  // @@protoc_insertion_point(class_scope:CommonRequest)
  private static final net.shengjian.rpc.grpcauto.CommonRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.shengjian.rpc.grpcauto.CommonRequest();
  }

  public static net.shengjian.rpc.grpcauto.CommonRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommonRequest>
      PARSER = new com.google.protobuf.AbstractParser<CommonRequest>() {
    @java.lang.Override
    public CommonRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommonRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommonRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommonRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.shengjian.rpc.grpcauto.CommonRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

