// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcCommonService.proto

package net.shengjian.rpc.grpcauto;

public interface CommonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 serialize = 1;</code>
   * @return The serialize.
   */
  int getSerialize();

  /**
   * <code>bytes request = 2;</code>
   * @return The request.
   */
  com.google.protobuf.ByteString getRequest();
}
